### ISSUE TITLE
Crash when Array == 2

### ISSUE THREAD

**Issue by Oniiichan** [windmemory/PhotoCollectionView#1]
When the number of images is 2, the collection view crashes on swipe.

Tested on the demo source (setting 2 images).

**Comment by Oniiichan** [comment]
2015-02-10 00:56:36.933 PhotoCollectionView[5785:70334] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[**NSArrayI objectAtIndex:]: index 2 beyond bounds [0 .. 1]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001100f5f35 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000111c39bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x000000010ffee01e -[__NSArrayI objectAtIndex:] + 190
    3   PhotoCollectionView                 0x000000010fefeeb6 _TFC19PhotoCollectionView19PhotoCollevtionView19scrollViewDidScrollfS0_FCSo12UIScrollViewT_ + 422
    4   PhotoCollectionView                 0x000000010ff00eca _TToFC19PhotoCollectionView19PhotoCollevtionView19scrollViewDidScrollfS0_FCSo12UIScrollViewT_ + 58
    5   UIKit                               0x0000000110a15462 -[UIScrollView(UIScrollViewInternal) _notifyDidScroll] + 56
    6   UIKit                               0x0000000110a05a42 -[UIScrollView setContentOffset:] + 645
    7   UIKit                               0x0000000110a11cec -[UIScrollView _smoothScrollWithUpdateTime:] + 2850
    8   QuartzCore                          0x000000011491b747 _ZN2CA7Display15DisplayLinkItem8dispatchEv + 37
    9   QuartzCore                          0x000000011491b60f _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 315
    10  CoreFoundation                      0x000000011005df64 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 20
    11  CoreFoundation                      0x000000011005db25 __CFRunLoopDoTimer + 1045
    12  CoreFoundation                      0x0000000110020e5d __CFRunLoopRun + 1901
    13  CoreFoundation                      0x0000000110020486 CFRunLoopRunSpecific + 470
    14  GraphicsServices                    0x00000001141ec9f0 GSEventRunModal + 161
    15  UIKit                               0x0000000110981420 UIApplicationMain + 1282
    16  PhotoCollectionView                 0x000000010ff036be top_level_code + 78
    17  PhotoCollectionView                 0x000000010ff036fa main + 42
    18  libdyld.dylib                       0x0000000112413145 start + 1
    19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by windmemory** [comment]
Thanks for bringing the issue, actually I can't remember why this issue happens, I have already fixed this issue long time ago, but forgot to push my code, lol. Now I pushed my code, you could pull it and try again, let me know if there are any further problems. 
Thanks again for this issue!!
